apiVersion: apps/v1
kind: Deployment
metadata: 
  name: canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-test
      environment: canary
  template:
    metadata:
      labels:
        app: canary-test
        environment: canary
    spec:
      containers:
      - name: nginx
        image: linuxacademycontent/ckad-nginx:canary
        ports:
        - containerPort: 80

# 1st(old) version of the application's image is => linuxacademycontent/ckad-nginx:1.0.0
# 2nd(new) version of the application's image is => linuxacademycontent/ckad-nginx:canary