apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: alnafi-app
  template:
    metadata:
      name: nginx-2
      labels:
        app: alnafi-app
    spec:

      containers:
      - name: nginx-container
        image: nginx
