apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp
  labels:
    app: frontend-rc
    type: development
spec:
  selector:
    app: frontend
  template:
    metadata:
      name: al-nafi
      labels:
        app: frontend
    spec:
      containers:
      - name: alpha
        image: nginx
  replicas: 5
