apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: frontend-replicaset
    tier: development
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: al-nafi
      labels:
        app: myapp
    spec:
      containers:
      - name: alpha
        image: nginx
