apiVersion: v1
kind: Pod
metadata:
  name: sidecar-practice-pod
spec:
  containers:
  - name: main-container # 1st Container
    image: busybox:stable
    command: ['sh', '-c', 'echo "I am learning Kubernetes at Al-nafi." > /output-dir/data.txt; while true; do sleep 5; done' ]
    volumeMounts:
    - name: shared-volume 
      mountPath: /output-dir

  - name: sidecar-container # 2nd Container
    image: busybox:stable
    command: ['sh', '-c', 'while true; do cat /input-dir/data.txt; sleep 5; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /input-dir

  volumes:
  - name: shared-volume
    emptyDir: {}
