apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: blue
spec:
  containers:
  - name: internal
    image: kodekloud/webapp-conntest
    env:
    - name: APP_NAME
      value: Blue - MArketing Application
    - name: BG_COLOR
      value: blue
    ports:
    - containerPort: 8080
      protocol: TCP