apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 5
      activeDeadlineSeconds: 20
      parallelism: 3
      completions: 6
      template:
        spec:
          containers:
          - name: test-cronjob-container
            image: busybox:1.28
            command:
            - echo
            - This is a Test CronJob!!
          restartPolicy: Never
