apiVersion: batch/v1
kind: Job
metadata:
  name: dice-job
  namespace: default 
spec: 
  template:
    spec:
      containers:
      - name: dice-job-container
        image: kodekloud/throw-dice
      restartPolicy: Never
  backoffLimit: 4
  completions: 5
  parallelism: 3
